### ISSUE TITLE
[question] Is there a way to download the key to do ssh

### ISSUE THREAD

**Issue by mariotoffia** [udondan/cdk-ec2-key-pair#1]
Hi, I'm modifying the greegrass [workshop](https://github.com/aws-samples/aws-iot-greengrass-edge-analytics-workshop) to handle _Java_ instead of python for internal education. I would like to automate the deployment as much as possible and hence auto create key (if not existent) to use with the two ec2 instances (greengrass and node red).

You project is spot on for me, however is there a way to download the keys in order to do `ssh` to the ec2 instances?

(around the same functionality as `aws ec2 create-key-pair --key-name ee-default-keypair.pem | jq -r ".KeyMaterial" > ee-default-keypair.pem` if it is possible)

Cheers,
 Mario

**Comment by udondan** [comment]
Hi Mario,

so sorry, I don't know how I missed this issue. I didn't get any notification. 😕 

The private key is stored in the secrets manager. So if you want to download the private key you can use something like this:

```bash
aws secretsmanager get-secret-value --secret-id ec2-private-key/key-name --query SecretString --output text > ee-default-keypair.pem
```

Cheers,
Daniel

**Comment by udondan** [comment]
I also added this info the the readme :)

**Comment by mariotoffia** [comment]
Thanks!! :)
