### ISSUE TITLE
 jsii version 

### ISSUE THREAD

**Issue by D4repoTier** [udondan/cdk-ec2-key-pair#10]
Hello 
1. excellent job! 
2. I stumble across incompatibilities with jsii and my deployment failed. (just for info im numb in jsii so maybe is my mistake, if so please let me know) 
 ERROR: cdk-ec2-key-pair 1.2.2 has requirement jsii~=1.1.0, but you'll have jsii 1.5.0 

Thanks
R

**Comment by udondan** [comment]
Hi @D4repoTier,

can you let me know in which context you're getting this? You're building your own JSII module? And my package is a dependency of yours? Can you share your setup, maybe the package.json? Honestly, I have no idea how this could happen, but happy to try to support you if I can reproduce it.

Cheers,
Daniel

**Comment by D4repoTier** [comment]
Hello, 
what i found out is that error is thrown during installation. Module is installed despite the error. I have jsii==1.5.0 in my python venv. After adding cdk-ec2-key-pair to requirements.txt and run pip install then error is thrown. 

But module it self is working successfully generated certs and store it in sm! 

`pip3 install -r requirements.txt 
Obtaining file:///home/ec2-user/finca-iac/cdk/ec2 (from -r requirements.txt (line 1))
Requirement already satisfied: boto3 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.13.7)
Requirement already satisfied: requests in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.23.0)
Requirement already satisfied: aws_cdk.aws_elasticloadbalancingv2 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_ec2 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws_cdk.custom_resources in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_cognito in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_lambda_event_sources in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_iam in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_lambda in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_sqs in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_elasticloadbalancingv2_targets in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_route53 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_route53_targets in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_certificatemanager in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 16)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_kms in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 17)) (1.38.0)
Requirement already satisfied: aws_cdk.aws_secretsmanager in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from -r requirements.txt (line 18)) (1.38.0)
Collecting cdk_ec2_key_pair (from -r requirements.txt (line 19))
Requirement already satisfied: aws-cdk.core in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from ec2==0.0.1->-r requirements.txt (line 1)) (1.38.0)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from boto3->-r requirements.txt (line 3)) (0.3.3)
Requirement already satisfied: botocore<1.17.0,>=1.16.7 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from boto3->-r requirements.txt (line 3)) (1.16.7)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from boto3->-r requirements.txt (line 3)) (0.9.5)
Requirement already satisfied: idna<3,>=2.5 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from requests->-r requirements.txt (line 4)) (2020.4.5.1)
Requirement already satisfied: aws-cdk.aws-s3==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (1.38.0)
Requirement already satisfied: constructs<4.0.0,>=3.0.2 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: aws-cdk.aws-cloudwatch==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (1.38.0)
Requirement already satisfied: jsii<2.0.0,>=1.5.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: publication>=0.0.3 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (0.0.3)
Requirement already satisfied: aws-cdk.aws-logs==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_ec2->-r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws-cdk.cloud-assembly-schema==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_ec2->-r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws-cdk.cx-api==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_ec2->-r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-ssm==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_ec2->-r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws-cdk.region-info==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_ec2->-r requirements.txt (line 6)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-sns==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.custom_resources->-r requirements.txt (line 7)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-cloudformation==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.custom_resources->-r requirements.txt (line 7)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-apigateway==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-events==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-sns-subscriptions==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-s3-notifications==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-kinesis==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-dynamodb==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-s3-assets==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_lambda->-r requirements.txt (line 11)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-cloudfront==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_route53_targets->-r requirements.txt (line 15)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-elasticloadbalancing==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_route53_targets->-r requirements.txt (line 15)) (1.38.0)
Requirement already satisfied: aws-cdk.aws-sam==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws_cdk.aws_secretsmanager->-r requirements.txt (line 18)) (1.38.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from botocore<1.17.0,>=1.16.7->boto3->-r requirements.txt (line 3)) (2.8.1)
Requirement already satisfied: docutils<0.16,>=0.10 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from botocore<1.17.0,>=1.16.7->boto3->-r requirements.txt (line 3)) (0.15.2)
Requirement already satisfied: cattrs~=1.0.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from jsii<2.0.0,>=1.5.0->aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: typing-extensions~=3.7.4 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from jsii<2.0.0,>=1.5.0->aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (3.7.4.2)
Requirement already satisfied: attrs~=19.3.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from jsii<2.0.0,>=1.5.0->aws_cdk.aws_elasticloadbalancingv2->-r requirements.txt (line 5)) (19.3.0)
Requirement already satisfied: aws-cdk.aws-applicationautoscaling==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws-cdk.aws-dynamodb==1.38.0->aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
Requirement already satisfied: aws-cdk.assets==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws-cdk.aws-s3-assets==1.38.0->aws_cdk.aws_lambda->-r requirements.txt (line 11)) (1.38.0)
Requirement already satisfied: six>=1.5 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.17.0,>=1.16.7->boto3->-r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: aws-cdk.aws-autoscaling-common==1.38.0 in /home/ec2-user/workspace/finca-iac/env/lib/python3.7/site-packages (from aws-cdk.aws-applicationautoscaling==1.38.0->aws-cdk.aws-dynamodb==1.38.0->aws_cdk.aws_lambda_event_sources->-r requirements.txt (line 9)) (1.38.0)
ERROR: cdk-ec2-key-pair 1.2.2 has requirement jsii~=1.1.0, but you'll have jsii 1.5.0 which is incompatible.
Installing collected packages: cdk-ec2-key-pair, ec2
  Found existing installation: ec2 0.0.1
    Uninstalling ec2-0.0.1:
      Successfully uninstalled ec2-0.0.1
  Running setup.py develop for ec2
Successfully installed cdk-ec2-key-pair-1.2.2 ec2
(env) [ec2-user@ip-10-223-224-139 ec2]$ pip3 freeze
astroid==2.4.1
attrs==19.3.0
autopep8==1.5.2
aws-cdk.assets==1.38.0
aws-cdk.aws-apigateway==1.38.0
aws-cdk.aws-applicationautoscaling==1.38.0
aws-cdk.aws-autoscaling-common==1.38.0
aws-cdk.aws-certificatemanager==1.38.0
aws-cdk.aws-cloudformation==1.38.0
aws-cdk.aws-cloudfront==1.38.0
aws-cdk.aws-cloudwatch==1.38.0
aws-cdk.aws-cognito==1.38.0
aws-cdk.aws-dynamodb==1.38.0
aws-cdk.aws-ec2==1.38.0
aws-cdk.aws-elasticloadbalancing==1.38.0
aws-cdk.aws-elasticloadbalancingv2==1.38.0
aws-cdk.aws-elasticloadbalancingv2-targets==1.38.0
aws-cdk.aws-events==1.38.0
aws-cdk.aws-iam==1.38.0
aws-cdk.aws-kinesis==1.38.0
aws-cdk.aws-kms==1.38.0
aws-cdk.aws-lambda==1.38.0
aws-cdk.aws-lambda-event-sources==1.38.0
aws-cdk.aws-logs==1.38.0
aws-cdk.aws-rds==1.38.0
aws-cdk.aws-route53==1.38.0
aws-cdk.aws-route53-targets==1.38.0
aws-cdk.aws-s3==1.38.0
aws-cdk.aws-s3-assets==1.38.0
aws-cdk.aws-s3-notifications==1.38.0
aws-cdk.aws-sam==1.38.0
aws-cdk.aws-secretsmanager==1.38.0
aws-cdk.aws-sns==1.38.0
aws-cdk.aws-sns-subscriptions==1.38.0
aws-cdk.aws-sqs==1.38.0
aws-cdk.aws-ssm==1.38.0
aws-cdk.cloud-assembly-schema==1.38.0
aws-cdk.core==1.38.0
aws-cdk.custom-resources==1.38.0
aws-cdk.cx-api==1.38.0
aws-cdk.region-info==1.38.0
boto3==1.13.7
botocore==1.16.7
cattrs==1.0.0
cdk-constants==3.0.3
cdk-ec2-key-pair==1.2.2
certifi==2020.4.5.1
chardet==3.0.4
constructs==3.0.3
docutils==0.15.2
flake8==3.8.2
idna==2.9
importlib-metadata==1.6.0
isort==4.3.21
jmespath==0.9.5
jsii==1.5.0
lazy-object-proxy==1.4.3
mccabe==0.6.1
publication==0.0.3
pycodestyle==2.6.0
pyflakes==2.2.0
pylint==2.5.2
python-dateutil==2.8.1
requests==2.23.0
s3transfer==0.3.3
six==1.14.0
toml==0.10.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
wrapt==1.12.1
zipp==3.1.0`

I hope this helped. 
Thanks 
R

**Comment by udondan** [comment]
The JSII version should not matter, if you just _use_ the package. But then again I'm not too deep in JSII, so what do I know... :)

I have updated the JSII version today to 1.5.0. Hope that solves your problem.
