### ISSUE TITLE
IAM Role name too long

### ISSUE THREAD

**Issue by ilkomiliev** [udondan/cdk-ec2-key-pair#11]
Hi,

thanks for the great work! We have the problem that we are hitting the 64 chars limitation for the name of the IAM Role, which is generated for the CR lambda function. Is there any way to customize this?

```
1 validation error detected: Value '[long-stack-name]-CFN-Resource-Custom-EC2-Key-Pair' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 159aeed5-4122-43e2-91af-aee7aeb72118)
```

**Comment by udondan** [comment]
Hi @ilkomiliev,

thanks for the ticket. I just released version 1.3.0 which contains a new option to customize the prefix:

```typescript
const key = new KeyPair(this, 'A-Key-Pair', {
  name: 'a-key-pair',
  description: 'This is a Key Pair',
  resourcePrefix: 'Shorty'
});
```

That would create a role with the name `Shorty-CFN-Resource-Custom-EC2-Key-Pair`.

Let me know if that works four you.

Cheers,
Daniel
