### ISSUE TITLE
upgrade lambda node runtime to 18

### ISSUE THREAD

**Issue by RaviTejaKaruturi** [udondan/cdk-ec2-key-pair#149]
Support for both Node.js 14.x, 16.x runtimes on AWS Lambda ends this year (phase 1 in Oct 10, 2023). So, upgrade runtime to 18.x.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Edit: Node 16.x deprecation (Phase 1) changed to March 11, 2024

**Comment by udondan** [comment]
Or you could just send a merge request

**Comment by lokulin** [comment]
> Or you could just send a merge request

https://github.com/udondan/cdk-ec2-key-pair/pull/150

**Comment by udondan** [comment]
There's a little bit more to it. The Lambda runtime with node up to 16 includes the aws-sdk v2. Starting with node 18 it includes the aws-sdk v3. So the Lamnda code needs to me migrated.
