### ISSUE TITLE
Using this module in conjunction with aws_codepipeline renders cloudformation templates unusable 

### ISSUE THREAD

**Issue by paveljos** [udondan/cdk-ec2-key-pair#15]
As in the title, when you utilize this module along with aws_codepipeline, if you render the cloudformation templates with "cdk synth", the resulting templates require you to set AssetParameters for the artifact hash, s3 bucket, and s3 version key. With no default value specified, the templates fail to install unless those values are set.  While that may be possible programmatically, I haven't surmised how to generate those values from CDK.

**Comment by udondan** [comment]
Hi @paveljos,

the construct creates a custom resource which is backed by a [Lambda function](https://github.com/udondan/cdk-ec2-key-pair/tree/master/lambda).

The CDK would take care of all the asset handling, but when you synthesize and deploy the template in a separate step you need to take care of the assets yourself. In another construct of mine I have described how you can build and upload the Lambda manually: https://github.com/udondan/cdk-ssm-document#using-the-lambda-as-a-custom-resource-in-cloudformation---without-cdk

Then you need to fill in the parameters for S3 bucket and key, the hash probably is an md5 sum of the zip, not sure.

Hope that helps.

Cheers,
Daniel
