### ISSUE TITLE
Duplicate IAM policy/role name when deploying multi region

### ISSUE THREAD

**Issue by jxia-innablr** [udondan/cdk-ec2-key-pair#183]
When deploying the key pair to a 2nd region, got below error:

A policy called SharedResources-dev-CFN-Resource-Custom-EC2-Key-Pair already exists. Duplicate names are not allowed

Looks like it is creating the same IAM role and policy again.

Could you please advise ?

**Comment by udondan** [comment]
Wow, that's something I never considered. 🙂 Need to take a look but might take a while until I find the time.
