### ISSUE TITLE
CDK version mismatch issues

### ISSUE THREAD

**Issue by fongie** [udondan/cdk-ec2-key-pair#20]
Hi! Thank you for creating this library.

When doing our latest CI build it failed on `yarn` because:
`error An unexpected error occurred: "expected hoisted manifest for \"cdk-ec2-key-pair#@aws-cdk/aws-lambda#@aws-cdk/aws-cloudwatch#@aws-cdk/core\"".`

Googling this suggests removing yarn.lock will do, but it didnt. However, we were running pinned cdk versions 1.74.0 in our packages and there was a new version 1.75.0 available. Updating to 1.75.0 solved the issue.

It seems that this happened because cdk-ec2-key-pair has caret version dependencies on CDK libraries. CDK version mismatch keeps causing issues for us, which is why we pin them.

It hinders our use of this library as we generally do not wish to be forced to update to the newest cdk version everytime it is released (even though we keep pretty up to date)

edit: I had a suggestion to use peer dependencies instead but.. they were already there. Any ideas on how to solve this issue?

**Comment by udondan** [comment]
Hi Max,

sorry for not responding sooner. Yeah, the CDK dependency version mismatch is a problem I have not found a solution yet and I don't think there is one acceptable. The peer dependencies don't work either. I have already tried that. As long as there is a caret ref, it will always install the latest version and that of course only works if you're as well using the latest version in your app.

What I think _could_ work is, to manually mess with the `package-lock.json`/`yarn.lock` after installation and change the nested dependencies to the version you're using. I'll explore that when I find some time and might release a tool to install cdk dependencies based on that.

I'm sorry I have no better solution for you at the moment.

There's another issue I wrote more regarding the problem https://github.com/udondan/cdk-ssm-document/pull/10#issuecomment-750195587

Cheers,
Daniel

**Comment by udondan** [comment]
I think I have figured this out now. If you want, you can try release 1.7.3. I was able to run this with CDK 1.80.0 and **1.70.0**.

The CDK dependencies now are only registered as peer dependencies. So you will also need to have those packages installed in the expected version:

- @aws-cdk/aws-cloudformation
- @aws-cdk/aws-ec2
- @aws-cdk/aws-iam
- @aws-cdk/aws-lambda

(At least here on my machine npm no longer warns about missing peer dependencies. I remember it did...)

Let me know if this doesn't work for you.

Cheers,
Daniel

**Comment by fongie** [comment]
Looks like it worked! I upped to 1.7.3 and it worked without upgrading CDK. Thanks for your help =)
