### ISSUE TITLE
Migrate to newer AWS Lambda runtime

### ISSUE THREAD

**Issue by jkoelewijn** [udondan/cdk-ec2-key-pair#27]
As stated on https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html, the support for the Node.js 10.x runtime on AWS Lambda ends this year (in two fases on July 30, 2021 and on Aug 30, 2021).

The custom CloudFormation resource should use a newer version of Node.js for the AWS Lambda function, preferably Node.js 14.

**Comment by udondan** [comment]
Thanks Jaap for pointing this out! I have totally missed that it's still using node 10. An updated version using node 14 has been published as version 2.2.0
