### ISSUE TITLE
Inconsistent names of name and keyPairName

### ISSUE THREAD

**Issue by ilko-rbi** [udondan/cdk-ec2-key-pair#30]
Hi,

I was confused by the fact that the constructor property for the key name is still called `name`, but the access property is renamed to `keyPairName`. Also the release notes stated that the constructor property was renamed - or have I misunderstood something? It would be nice to have a consistent names to avoid this confusion.

Thanks!

**Comment by ilko-rbi** [comment]
ok, I've misread construct with constructor - nevertheless, the inconsistent names are still confusing IMHO...

**Comment by udondan** [comment]
I guess you're right. To be more consistent with the core cdk modules, the `name` prop should be renamed `keyPairName`. I think that's how it's done everywhere in the core.
