### ISSUE TITLE
Python documentation completely missing

### ISSUE THREAD

**Issue by DrCord** [udondan/cdk-ec2-key-pair#328]
The python documentation is lacking - without even a clear way to import it in a file once installed to get started.

**Comment by udondan** [comment]
The package is made available for various language via jsii. I believe the TypeScript documentation should provide a solid foundation for developers to adapt the code to their language of choice. 

I'm wondering if you actually missed the fact that this is a package for AWS CDK, not to be used standalone, as I think anyone who worked with AWS CDK would know how to generally import and use a construct.
