### ISSUE TITLE
cdk-iam-floyd considered harmful

### ISSUE THREAD

**Issue by ahammond** [udondan/cdk-ec2-key-pair#48]
When I try to use this construct in another construct, I end up in dependency hell because of cdk-iam-floyd. Would you accept a PR that removes it?

**Comment by udondan** [comment]
Yes, I had actually planned to remove it myself. Since the policy is static and won't change it doesn't give any benefit.

**Comment by simon-two** [comment]
Also noticed that updating to CDK 2.20.0 causes problems since this needs a newer cdk-iam-floyd version ( >= v0.351.0)
