### ISSUE TITLE
names function but doesn't constrain name length

### ISSUE THREAD

**Issue by ahammond** [udondan/cdk-ec2-key-pair#53]
```
❯ npx cdk list

/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/aws-cdk-lib/aws-lambda/lib/function.ts:662
        throw new Error(`Function name can not be longer than 64 characters but has ${props.functionName.length} characters.`);
              ^
Error: Function name can not be longer than 64 characters but has 74 characters.
    at new Function (/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/aws-cdk-lib/aws-lambda/lib/function.ts:662:15)
    at KeyPair.ensureLambda (/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/cdk-ec2-key-pair/lib/index.ts:369:16)
    at new KeyPair (/Users/ahammond/Documents/ClickUp/cold-storage-cdk/node_modules/cdk-ec2-key-pair/lib/index.ts:214:24)
```

**Comment by ahammond** [comment]
This popped up when I tried to deploy using a CdkPipeline. I'm guessing the pipelines do stupid tricks with the names.

**Comment by ahammond** [comment]
Ah, I see in the code that it's testing to confirm the function name isn't too long, and throwing. So, the workaround is to use the `resourcePrefix`. But... why give the function an explicit name at all? That's just asking for trouble.

**Comment by ahammond** [comment]
Oh man. So when I just set the prefix to "x", I get collisions when I try to deploy multiples of these in an environment. Having a name on this function is not a feature. It's just a source of problems.

**Comment by armhzjz** [comment]
> Ah, I see in the code that it's testing to confirm the function name isn't too long, and throwing. So, the workaround is to use the `resourcePrefix`. But... why give the function an explicit name at all? That's just asking for trouble.

Hello @ahammond,
when you wrote you used the `resourcePrefix` as a workaround, did you maybe mean `secretPrefix`?
I can't seem to find any `resourcePrefix` in the documentation.

**Comment by udondan** [comment]
Sorry guys. My amount of time for OS currently is negative.

You could just use the CDK escape hatches to get around this. The Lambda is exposed as a resource property.

```ts
const cfnFunction = keyPair.lambda.node.defaultChild as cdk.aws_lambda.CfnFunction;

const cfnRole = keyPair.lambda.role!.node.defaultChild as cdk.aws_iam.CfnRole;

cfnFunction.addPropertyDeletionOverride('FunctionName');
cfnRole.addPropertyDeletionOverride('RoleName');
```

Unfortunately the policy is not exposed. But you could visit it via aspects. Something like this:

```ts
cdk.Aspects.of(this).add(new RemovePolicyName(this));
```

```ts
export class RemovePolicyName implements cdk.IAspect {
  constructor(stack: cdk.Stack) {}

  public visit(construct: IConstruct): void {
    if (construct instanceof cdk.aws_iam.Policy) {
      const cfnPolicy = construct.node.defaultChild as cdk.aws_iam.CfnPolicy;
      cfnPolicy.addPropertyDeletionOverride('PolicyName');
    }
  }
}
```

**Comment by armhzjz** [comment]
Hi @udondan ,

thanks for the hint.
Unfortunately, at least for the python implementations, this will not work.
It seems that when using CDK escape hatches, you are expected to operate on an already existing object.
But the object does not exist - cdk throws the reported exception when trying to create an instance of it (i.e., of the KeyPair object).

Could you give us an estimation of more or less when could we expect the solution of #54 to be merged?
(Not trying to push nobody in any way)

**Comment by udondan** [comment]
Think I'm going to deprecate this package. CFN now supports creation of KeyPairs and this feature now is available since CDK 2.29.0. 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnKeyPair.html

Havent tested it yet. The only difference seems to be it stores the key in ssm paramater instead of secret. If that realy all works there is no need for this package any longer.

**Comment by udondan** [comment]
NOT going to deprecate this. 😸 The CfnKeyPair is generally working and certainly does the trick for most use cases. But it does unfortunately not cover everyting this construct does. Directly accessing the public and private keys from CDK and forwarding it to other resources was the blocker in my use cases.

**Comment by udondan** [comment]
For visibility, I'll quote my [comment](https://github.com/udondan/cdk-ec2-key-pair/pull/54#issuecomment-1722846139) here:

> Personally I do not have a problem with this. Though AWS does. You cannot change the Lambda function name for **existing** custom resources. CFN will fail with:
> 
> > Modifying service token is not allowed.
> 
> By removing the function name we would force all users to delete and re-create their KeyPairs. 
> 
> I see only one option how we can change this: A new contruct property, e.g. `lambdaName`. 
> 
> - If `undefined`: We use the name as currently implemented. So this is backwards compatible and not messing with existing KeyPairs
> - If `false`: No names for the function, role and policy will be set
> - If `typeof String`: User can set a custom name
